# Site settings
title: Lou Groshek
description: Lou Groshek is a web developer specializing in HUGO, React.js, Gatbsby, Adapt, SCORM, Moodle, WordPress, internationalization, and accessibility.
keywords: lou, amy, groshek, developer, hugo, golang, adapt, react, gatsby, node, scorm, internationalization, li0n, accessibility, a11y, angular
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lou Groshek
user_description: <p><strong>Hi! My name is Lou</strong>, and I'm a freelance web developer specializing in static site generators including Gatsby, Jekyll, and HUGO. I have experience with a11y, AWS, Google Analytics, and the Adapt Framework for online learning content. My expertise also includes SCORM, Moodle, and WordPress online learning plugins like LearnDash and Edwiser.</p><p>I have 10 years of experience in the online learning industry, and I got my start doing front-end and PHP development for the Moodle LMS. What I love most about freelancing is that I am constantly learning new programming languages and frameworks. I prefer clients invested in elegant, efficient, and future-forward solutions with minimal technical debt. If you ask me for something that's not a very good idea, I'm sure to tell you so. <strong>;)</strong></p>
user_title: Web Developer and Online Learning Consultant
email: lou@lougroshek.com
twitter_username: lougroshek
github_username: lougroshek
# gplus_username:  lorem_ipsum
linkedin_username: amy-groshek-b7a2683

# Google-analytics
google-analytics:
  id: "UA-126172720-1"

exclude: ["package.json", "src", "node_modules"]

sass:
  sass_dir: _sass
# theme: jekyll-theme-cayman
